### PR TITLE
allow ids for rune placement, add conditions, ruin actor interface

### PR DESCRIPTION
**Pull request by liqMix**
Opening this here because i discust myself with rushed shoehorned features

### CODE REVIEW

**Comment by liqMix** [comment]
i felt bad adding so much junk to the actor interface, theres probably a better architecture for this

**Comment by kettek** [comment]
Seems to be okay. Let me know if my assumption about ActorID -> ID was correct.

I might minimize the Actor interface further, such as removing the Player/SetPlayer stuff, but we'll see.

Also might be good to actually have ID as the interface, in case we want to use it to identify Player1/Player2 via the same ID system.

**Comment by kettek** [comment]
At any rate, this seems good for now.

**Review by kettek — APPROVED** [review]
ALL GOOD IN THE HOOD

**Comment by liqMix** [comment]
Thanks for cleaning up my messie

**Pull request merged**
